FF-232   Update Script stable
FileFighter/ClientSetup pull request #9
Opened 2020-12-20 11:13 UTC by qvalentin

2020-12-20 12:23 UTC, open-schnick commented on config.cfg
> +db_password=BXEyIBFxVoOwpNyJgGWFuNmQRrsYPOiKBYlpunIHtXOzoOrQAR
bruh.

2020-12-20 12:26 UTC, open-schnick commented
Looks fine to me, didnt test it.

2020-12-20 15:25 UTC, open-schnick commented on lib/update.sh
> +    echo "Password was not set, please install first."
oks set the password in your config `configPath` or run 'ffigther install' again.

2020-12-20 15:26 UTC, open-schnick commented on lib/update.sh
> +
what are these spaces xd

2020-12-20 15:28 UTC, open-schnick commented on lib/update.sh
> + exit 1
maybe we should start listing deps we need.

- docker
- wget / curl
- regctl

2020-12-20 15:28 UTC, open-schnick commented on lib/update.sh
> +
xd

2020-12-20 15:28 UTC, open-schnick commented on lib/update.sh
> +
xDDDD

2020-12-20 15:29 UTC, open-schnick requested changes
Maybe Clean it up a bit. But does look good. Did you test it?

2020-12-20 15:55 UTC, qvalentin commented
You can test the latest update by installing the stable version, then changing the config to use latrst and then running update. Run it twice, the second time it should not update.

Stable update can be tested when we reales new tags in the two repos.

2020-12-21 15:19 UTC, open-schnick approved these changes
I fixed minor spelling and bumped up version to 1.5. Also tested it and looks fine.

2020-12-21 15:19 UTC, merged